// AUTO-GENERATED by scripts/optimize-paintings.mjs — do not edit by hand.
// Basenames (no extension) that have an optimized WebP in /images/opt/.
export const OPTIMIZED = new Set([
  "founder-portrait",
  "hero-horseman",
  "oil-become",
  "oil-closing",
  "oil-faq",
  "oil-founder",
  "oil-naval",
  "oil-offering",
  "oil-operate",
  "oil-principles",
  "oil-testimony",
  "truth-destruction"
])
