/**
 * All copy in one place. Replace bracketed slots with real copy.
 * Format: [ Label ] — terse, clear, one purpose per slot.
 * Roman numerals (I, II, III…) are structural design — leave them.
 * Field labels in the application form are kept functional so the form is usable
 * during draft review.
 */

export const heroContent = {
  eyebrow: '[ Eyebrow — 1–3 words ]',
  headline: '[ Headline — 3–7 words ]',
  restraint: '[ Restraint line — single line under CTA ]',
  cta: '[ CTA button ]',
}

export const truthContent = {
  eyebrow: 'I',
  heading: '[ Heading — names the condition ]',
  paragraphs: [
    '[ Paragraph 1 ]',
    '[ Paragraph 2 ]',
    '[ Paragraph 3 ]',
  ],
  turn: '[ Turn line — italic, the pivot ]',
  // Panel from the Saturday infographic. Generated by: npm run crop:saturday
  image: '/images/panel-window.jpg',
  imageAlign: 'right',
}

/**
 * THE CODE — values / standards / what WE hold.
 * Three principles. One line each. Carved.
 */
export const codeContent = {
  eyebrow: 'II',
  heading: 'The Code',
  intro: '[ Intro — what we hold (optional) ]',
  image: '/images/panel-iron.jpg',
  imageAlign: 'left',
  principles: [
    { roman: 'I',   text: 'Integrity.' },
    { roman: 'II',  text: 'Loyalty.' },
    { roman: 'III', text: 'Competence.' },
  ],
}

/**
 * WHAT YOU BECOME — outcomes / yield / what YOU receive.
 * Three blocks. Concrete, not promises. This is the value the applicant gets.
 */
export const becomeContent = {
  eyebrow: 'III',
  heading: 'What You Become',
  // Group running — the active result, brotherhood in motion.
  image: '/images/panel-running.jpg',
  imageAlign: 'full',
  blocks: [
    {
      title: '[ Outcome 1 title ]',
      body: '[ Outcome 1 — what you receive in this area ]',
    },
    {
      title: '[ Outcome 2 title ]',
      body: '[ Outcome 2 — what you receive in this area ]',
    },
    {
      title: '[ Outcome 3 title ]',
      body: '[ Outcome 3 — what you receive in this area ]',
    },
  ],
}

export const consideredContent = {
  eyebrow: 'IV',
  heading: '[ Heading — 2–4 words ]',
  for_: '[ Apply if… line ]',
  not: '[ Do not apply if… line ]',
  // Panel from the Saturday infographic — library reading.
  image: '/images/panel-library.jpg',
  imageAlign: 'right',
}

export const founderContent = {
  eyebrow: 'V',
  heading: '[ Heading — e.g. From the Founder ]',
  placeholderMark: '[ Founder portrait ]',
  paragraphs: [
    '[ Paragraph 1 — who he is ]',
    '[ Paragraph 2 — what he saw missing ]',
    '[ Paragraph 3 — the invitation ]',
  ],
  signature: '[ — Founder name, year ]',
  templated: true,
  // Full-bleed bg behind founder content.
  image: '/images/panel-cold.jpg',
  imageAlign: 'full',
}

/**
 * Evidence (testimony) section — currently hidden in App.jsx until first cohort
 * completes. Copy kept here so it's ready when re-enabled.
 */
export const evidenceContent = {
  eyebrow: 'VI',
  heading: '[ Heading — e.g. Testimony ]',
  intro: '[ Intro line ]',
  cards: [
    { quote: '[ Testimony 1 ]', attribution: '[ Name — year ]' },
    { quote: '[ Testimony 2 ]', attribution: '[ Name — year ]' },
    { quote: '[ Testimony 3 ]', attribution: '[ Name — year ]' },
  ],
  templated: true,
}

export const faqContent = {
  eyebrow: 'VI',
  heading: '[ Heading — e.g. Questions a serious man asks ]',
  image: '/images/panel-sauna.jpg',
  imageAlign: 'left',
  items: [
    { q: '[ Q1 ]', a: '[ A1 ]' },
    { q: '[ Q2 ]', a: '[ A2 ]' },
    { q: '[ Q3 — religion / cross ]', a: '[ A3 ]' },
    { q: '[ Q4 — cost ]', a: '[ A4 ]' },
    { q: '[ Q5 — differentiation ]', a: '[ A5 ]' },
  ],
}

export const footerContent = {
  restraint: '[ Footer line — one philosophical line ]',
  copyright: '© The Order',
  privacyHref: 'https://wayfindercollective.io/privacy',
}

export const finalScreenContent = {
  heading: '[ Final heading ]',
  sub: '[ Sub line ]',
  begin: '[ Encouragement — italic ]',
}

export const applicationCopy = {
  eyebrow: 'The Application',
  heading: '[ Heading ]',
  sub: '[ Sub ]',
  submitButton: '[ Submit button ]',
  submittingButton: 'Submitting…',
  // Full-bleed bg behind the form card.
  image: '/images/panel-journal.jpg',
  imageAlign: 'full',
}

export const formCopy = {
  nameLabel: 'Full name',
  namePlaceholder: '[ Name hint ]',
  emailLabel: 'Email',
  emailPlaceholder: '[ Email hint ]',
  phoneLabel: 'Phone',
  phonePlaceholder: 'Number',
  emailError: 'That email does not look right.',
  phoneError: 'That number does not look right.',
}

/**
 * SMS consent — TCPA-compliant copy. Replace the sender entity when Wayfinder
 * confirms the registered SMS sender for this funnel.
 */
export const submitConsent = {
  smsLine: 'I consent to receive SMS communications from Wayfinder Coaching about my application. Message and data rates may apply. Reply STOP to opt out at any time.',
}

/**
 * HERO FILM — the cinematic asset shown behind the headline.
 *
 * Three options, in order of preference:
 *   1. video: { src, poster } — a single short clip, scroll-scrubbed (gold standard)
 *   2. frames: [{ src }, ...] — 4–8 stills, crossfaded as user scrolls
 *   3. neither — clean dark hero with no imagery (current state until assets exist)
 *
 * See THE_ORDER_PLAN.md §18 for AI-generation prompts.
 */
export const heroFilm = {
  video: null,   // { src: '/hero/film.mp4', poster: '/hero/poster.jpg' }
  // Single fallback frame so the hero isn't empty until a video lands.
  // Swap to a richer multi-frame sequence later.
  frames: [
    { src: '/images/panel-brothers.jpg' },
  ],
}
